apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: test-cronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: test-cronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - date;
            - echo
            - hello from kubernetes cluster
            image: busybox
            name: test-cronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
